version: '3'
services:
  node_app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: node_app
    command: npm run server
    environment:
      DB_HOSTNAME: mysql_database
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      EMAIL_FROM: ${EMAIL_FROM}
      PROJECT_URL: ${PROJECT_URL}
      PROJECT_PORT: ${PROJECT_PORT}
    ports:
      - "3000:3000"
    volumes:
      - ./src/:/usr/src/node-app/src
    networks:
      - my-network

  mysql_database:
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ALLOW_EMPTY_PASSWORD:
      MYSQL_RANDOM_ROOT_PASSWORD:
    volumes:
      - bienes-raices-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  bienes-raices-data: